BASE_MARKET = 'BTC'

PERIOD_SEG = 20

#UPDATE_MARKET_CACHE_EACH_X_MIN = 60
UPDATE_MARKET_CACHE_EACH_X_MIN = 5

LENGTH_ARRAY_PRICES = UPDATE_MARKET_CACHE_EACH_X_MIN * 60 / PERIOD_SEG

SELL_OLD_MARKETS_PERIOD = 10
#SELL_OLD_MARKETS_PERIOD = 10

QUARANTINE_TIME_TO_BUY = 5

NUM_MARKETS_TO_BUY = 10

COMMISSION = 0.25

BTC_QUANTITY_TO_BUY = 0.0005

BTC_INITIAL_BALANCE = ((BTC_QUANTITY_TO_BUY * NUM_MARKETS_TO_BUY) + (BTC_QUANTITY_TO_BUY * COMMISSION / 100 * NUM_MARKETS_TO_BUY)).round(8)

GAIN_ON_THE_DAY_THRESHOLD = 15

VOLUME_BOTTOM_THRESHOLD_OF_GROWTH = 0

BOTTOM_THRESHOLD_OF_GROWTH = 0

CEIL_THRESHOLD_OF_GROWTH = 1

THRESHOLD_OF_LOST = 100

THRESHOLD_OF_GAIN = 5

ASK_THRESHOLD = 0

BID_THRESHOLD = 0

BID_MEAN_GROWTH = 3

PERIOD_GROWTH = 30

TREND_GROWTH = 5

BUY_ETH_MARKET = false

BUY_BITCNY_MARKET = false

BUY_USDT_MARKET = false

PERCENTILE_VOLUME = 33

PERCENTILE_ASK_BID = 66

PERCENTAGE_TO_LOSE_OLD_MARKETS = 0.33

SPREAD_LIMIT = 1

DIFF_MAX_PRICE = 1

